# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'masewa.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/gallery/lipstick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 559))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setSpacing(51)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(30, 71, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.sales_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sales_btn.sizePolicy().hasHeightForWidth())
        self.sales_btn.setSizePolicy(sizePolicy)
        self.sales_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sales_btn.setSizeIncrement(QtCore.QSize(16, 0))
        self.sales_btn.setStyleSheet("QPushButton{                      \n"
"                    background: transparent;\n"
"                }  \n"
"                ")
        self.sales_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/gallery/sales.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sales_btn.setIcon(icon1)
        self.sales_btn.setIconSize(QtCore.QSize(66, 66))
        self.sales_btn.setObjectName("sales_btn")
        self.verticalLayout.addWidget(self.sales_btn)
        self.products_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(19)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.products_btn.sizePolicy().hasHeightForWidth())
        self.products_btn.setSizePolicy(sizePolicy)
        self.products_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.products_btn.setSizeIncrement(QtCore.QSize(16, 0))
        self.products_btn.setStyleSheet("QPushButton{                      \n"
"                    background: transparent;\n"
"                }  \n"
"                ")
        self.products_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/gallery/cosmetic1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.products_btn.setIcon(icon2)
        self.products_btn.setIconSize(QtCore.QSize(66, 66))
        self.products_btn.setObjectName("products_btn")
        self.verticalLayout.addWidget(self.products_btn)
        self.users_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.users_btn.sizePolicy().hasHeightForWidth())
        self.users_btn.setSizePolicy(sizePolicy)
        self.users_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.users_btn.setSizeIncrement(QtCore.QSize(16, 0))
        self.users_btn.setStyleSheet("QPushButton{                      \n"
"                    background: transparent;\n"
"                }  \n"
"                ")
        self.users_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/gallery/users.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.users_btn.setIcon(icon3)
        self.users_btn.setIconSize(QtCore.QSize(66, 66))
        self.users_btn.setObjectName("users_btn")
        self.verticalLayout.addWidget(self.users_btn)
        self.suppliers_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.suppliers_btn.sizePolicy().hasHeightForWidth())
        self.suppliers_btn.setSizePolicy(sizePolicy)
        self.suppliers_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.suppliers_btn.setSizeIncrement(QtCore.QSize(16, 0))
        self.suppliers_btn.setStyleSheet("QPushButton{                      \n"
"                    background: transparent;\n"
"                }  \n"
"                ")
        self.suppliers_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/gallery/supply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.suppliers_btn.setIcon(icon4)
        self.suppliers_btn.setIconSize(QtCore.QSize(62, 79))
        self.suppliers_btn.setObjectName("suppliers_btn")
        self.verticalLayout.addWidget(self.suppliers_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 71, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout.setStretch(2, 25)
        self.verticalLayout.setStretch(3, 25)
        self.verticalLayout.setStretch(4, 25)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 5)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MainTab = QtWidgets.QTabWidget(self.centralwidget)
        self.MainTab.setObjectName("MainTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_31 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_6.addWidget(self.label_31)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sales_table = QtWidgets.QTableWidget(self.tab)
        self.sales_table.setObjectName("sales_table")
        self.sales_table.setColumnCount(6)
        self.sales_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sales_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sales_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sales_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sales_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sales_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sales_table.setHorizontalHeaderItem(5, item)
        self.gridLayout_4.addWidget(self.sales_table, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_sales_btn = QtWidgets.QPushButton(self.tab)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/gallery/money.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_sales_btn.setIcon(icon5)
        self.add_sales_btn.setIconSize(QtCore.QSize(20, 20))
        self.add_sales_btn.setObjectName("add_sales_btn")
        self.horizontalLayout.addWidget(self.add_sales_btn)
        self.refresh_btn = QtWidgets.QPushButton(self.tab)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/gallery/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_btn.setIcon(icon6)
        self.refresh_btn.setIconSize(QtCore.QSize(26, 18))
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout.addWidget(self.refresh_btn)
        self.export_btn = QtWidgets.QPushButton(self.tab)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/gallery/excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_btn.setIcon(icon7)
        self.export_btn.setIconSize(QtCore.QSize(26, 19))
        self.export_btn.setObjectName("export_btn")
        self.horizontalLayout.addWidget(self.export_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.MainTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.products_tab = QtWidgets.QTabWidget(self.tab_2)
        self.products_tab.setObjectName("products_tab")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.products_table = QtWidgets.QTableWidget(self.tab_3)
        self.products_table.setObjectName("products_table")
        self.products_table.setColumnCount(6)
        self.products_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.products_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.products_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.products_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.products_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.products_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.products_table.setHorizontalHeaderItem(5, item)
        self.gridLayout_2.addWidget(self.products_table, 0, 0, 1, 1)
        self.products_tab.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.p_name_entry = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_name_entry.sizePolicy().hasHeightForWidth())
        self.p_name_entry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.p_name_entry.setFont(font)
        self.p_name_entry.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p_name_entry.setDragEnabled(False)
        self.p_name_entry.setReadOnly(False)
        self.p_name_entry.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.p_name_entry.setClearButtonEnabled(True)
        self.p_name_entry.setObjectName("p_name_entry")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.p_name_entry)
        spacerItem2 = QtWidgets.QSpacerItem(24, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.categ_combo = QtWidgets.QComboBox(self.groupBox_3)
        self.categ_combo.setObjectName("categ_combo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.categ_combo)
        spacerItem3 = QtWidgets.QSpacerItem(34, 46, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.p_price_entry = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_price_entry.sizePolicy().hasHeightForWidth())
        self.p_price_entry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.p_price_entry.setFont(font)
        self.p_price_entry.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p_price_entry.setStyleSheet("")
        self.p_price_entry.setInputMask("")
        self.p_price_entry.setText("")
        self.p_price_entry.setClearButtonEnabled(False)
        self.p_price_entry.setObjectName("p_price_entry")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.p_price_entry)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.p_qnty_entry = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_qnty_entry.sizePolicy().hasHeightForWidth())
        self.p_qnty_entry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.p_qnty_entry.setFont(font)
        self.p_qnty_entry.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p_qnty_entry.setObjectName("p_qnty_entry")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.p_qnty_entry)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.p_supl_entry = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_supl_entry.sizePolicy().hasHeightForWidth())
        self.p_supl_entry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.p_supl_entry.setFont(font)
        self.p_supl_entry.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p_supl_entry.setObjectName("p_supl_entry")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.p_supl_entry)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cancel_prod_btn = QtWidgets.QPushButton(self.groupBox_3)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/gallery/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_prod_btn.setIcon(icon8)
        self.cancel_prod_btn.setIconSize(QtCore.QSize(26, 16))
        self.cancel_prod_btn.setObjectName("cancel_prod_btn")
        self.horizontalLayout_8.addWidget(self.cancel_prod_btn)
        self.categories_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.categories_btn.setObjectName("categories_btn")
        self.horizontalLayout_8.addWidget(self.categories_btn)
        self.save_prod_btn = QtWidgets.QPushButton(self.groupBox_3)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/gallery/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_prod_btn.setIcon(icon9)
        self.save_prod_btn.setIconSize(QtCore.QSize(26, 16))
        self.save_prod_btn.setObjectName("save_prod_btn")
        self.horizontalLayout_8.addWidget(self.save_prod_btn)
        self.formLayout.setLayout(10, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_8)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.gridLayout_9.addLayout(self.verticalLayout_3, 0, 0, 2, 1)
        self.add_categ_entry = QtWidgets.QLineEdit(self.tab_4)
        self.add_categ_entry.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_categ_entry.setFont(font)
        self.add_categ_entry.setClearButtonEnabled(True)
        self.add_categ_entry.setObjectName("add_categ_entry")
        self.gridLayout_9.addWidget(self.add_categ_entry, 1, 1, 1, 1)
        self.new_categ_btn = QtWidgets.QPushButton(self.tab_4)
        self.new_categ_btn.setEnabled(False)
        self.new_categ_btn.setObjectName("new_categ_btn")
        self.gridLayout_9.addWidget(self.new_categ_btn, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setStyleSheet("\n"
"image: url(:/gallery/cosmetic2.jpg);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 0, 1, 1, 2)
        self.products_tab.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 10, 0, 1, 1)
        self.p_name_entry_2 = QtWidgets.QLineEdit(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_name_entry_2.sizePolicy().hasHeightForWidth())
        self.p_name_entry_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.p_name_entry_2.setFont(font)
        self.p_name_entry_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p_name_entry_2.setDragEnabled(False)
        self.p_name_entry_2.setReadOnly(False)
        self.p_name_entry_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.p_name_entry_2.setObjectName("p_name_entry_2")
        self.gridLayout_10.addWidget(self.p_name_entry_2, 3, 0, 1, 1)
        self.p_qnty_entry2 = QtWidgets.QLineEdit(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_qnty_entry2.sizePolicy().hasHeightForWidth())
        self.p_qnty_entry2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.p_qnty_entry2.setFont(font)
        self.p_qnty_entry2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p_qnty_entry2.setObjectName("p_qnty_entry2")
        self.gridLayout_10.addWidget(self.p_qnty_entry2, 7, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem7, 0, 1, 1, 1)
        self.search_prod_entry = QtWidgets.QLineEdit(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.search_prod_entry.setFont(font)
        self.search_prod_entry.setObjectName("search_prod_entry")
        self.gridLayout_10.addWidget(self.search_prod_entry, 0, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_5)
        self.label_26.setStyleSheet("image: url(:/gallery/three-black.jpg);")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 1, 1, 4, 1)
        self.p_supl_entry2 = QtWidgets.QLineEdit(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_supl_entry2.sizePolicy().hasHeightForWidth())
        self.p_supl_entry2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.p_supl_entry2.setFont(font)
        self.p_supl_entry2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p_supl_entry2.setObjectName("p_supl_entry2")
        self.gridLayout_10.addWidget(self.p_supl_entry2, 11, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.delete_prod_btn = QtWidgets.QPushButton(self.tab_5)
        self.delete_prod_btn.setEnabled(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/gallery/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_prod_btn.setIcon(icon10)
        self.delete_prod_btn.setIconSize(QtCore.QSize(26, 26))
        self.delete_prod_btn.setObjectName("delete_prod_btn")
        self.horizontalLayout_3.addWidget(self.delete_prod_btn)
        spacerItem8 = QtWidgets.QSpacerItem(36, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.save_prod_edit_btn = QtWidgets.QPushButton(self.tab_5)
        self.save_prod_edit_btn.setEnabled(True)
        self.save_prod_edit_btn.setIcon(icon9)
        self.save_prod_edit_btn.setIconSize(QtCore.QSize(26, 26))
        self.save_prod_edit_btn.setObjectName("save_prod_edit_btn")
        self.horizontalLayout_3.addWidget(self.save_prod_edit_btn)
        self.gridLayout_10.addLayout(self.horizontalLayout_3, 20, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setStyleSheet("image: url(:/gallery/eyeshadow.jpg);")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.gridLayout_10.addWidget(self.label_29, 11, 1, 3, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setObjectName("label_10")
        self.gridLayout_10.addWidget(self.label_10, 2, 0, 1, 1)
        self.categ_combo2 = QtWidgets.QComboBox(self.tab_5)
        self.categ_combo2.setObjectName("categ_combo2")
        self.gridLayout_10.addWidget(self.categ_combo2, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 4, 0, 1, 1)
        self.search_prod_btn = QtWidgets.QPushButton(self.tab_5)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/gallery/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_prod_btn.setIcon(icon11)
        self.search_prod_btn.setIconSize(QtCore.QSize(30, 23))
        self.search_prod_btn.setObjectName("search_prod_btn")
        self.gridLayout_10.addWidget(self.search_prod_btn, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setObjectName("label_7")
        self.gridLayout_10.addWidget(self.label_7, 8, 0, 1, 1)
        self.p_price_entry_2 = QtWidgets.QLineEdit(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_price_entry_2.sizePolicy().hasHeightForWidth())
        self.p_price_entry_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.p_price_entry_2.setFont(font)
        self.p_price_entry_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p_price_entry_2.setObjectName("p_price_entry_2")
        self.gridLayout_10.addWidget(self.p_price_entry_2, 9, 0, 1, 1)
        self.products_tab.addTab(self.tab_5, "")
        self.horizontalLayout_2.addWidget(self.products_tab)
        self.MainTab.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.add_user_box = QtWidgets.QGroupBox(self.tab_6)
        self.add_user_box.setAlignment(QtCore.Qt.AlignCenter)
        self.add_user_box.setObjectName("add_user_box")
        self.formLayout_3 = QtWidgets.QFormLayout(self.add_user_box)
        self.formLayout_3.setObjectName("formLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem9)
        self.label_12 = QtWidgets.QLabel(self.add_user_box)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.add_uname = QtWidgets.QLineEdit(self.add_user_box)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_uname.setFont(font)
        self.add_uname.setClearButtonEnabled(True)
        self.add_uname.setObjectName("add_uname")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.add_uname)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem10)
        self.label_13 = QtWidgets.QLabel(self.add_user_box)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.add_email = QtWidgets.QLineEdit(self.add_user_box)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_email.setFont(font)
        self.add_email.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.add_email.setClearButtonEnabled(True)
        self.add_email.setObjectName("add_email")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.add_email)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem11)
        self.label_14 = QtWidgets.QLabel(self.add_user_box)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.add_psd = QtWidgets.QLineEdit(self.add_user_box)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_psd.setFont(font)
        self.add_psd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.add_psd.setClearButtonEnabled(True)
        self.add_psd.setObjectName("add_psd")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.add_psd)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem12)
        self.label_15 = QtWidgets.QLabel(self.add_user_box)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.add_psd2 = QtWidgets.QLineEdit(self.add_user_box)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_psd2.setFont(font)
        self.add_psd2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.add_psd2.setClearButtonEnabled(True)
        self.add_psd2.setObjectName("add_psd2")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.add_psd2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(8, QtWidgets.QFormLayout.FieldRole, spacerItem13)
        self.inv_psd_lbl = QtWidgets.QLabel(self.add_user_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inv_psd_lbl.setFont(font)
        self.inv_psd_lbl.setStyleSheet("color: rgb(255, 0, 0);")
        self.inv_psd_lbl.setText("")
        self.inv_psd_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.inv_psd_lbl.setObjectName("inv_psd_lbl")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.inv_psd_lbl)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cancel_user_btn = QtWidgets.QPushButton(self.add_user_box)
        self.cancel_user_btn.setIcon(icon8)
        self.cancel_user_btn.setIconSize(QtCore.QSize(26, 16))
        self.cancel_user_btn.setObjectName("cancel_user_btn")
        self.horizontalLayout_6.addWidget(self.cancel_user_btn)
        self.add_user_btn = QtWidgets.QPushButton(self.add_user_box)
        self.add_user_btn.setIcon(icon9)
        self.add_user_btn.setIconSize(QtCore.QSize(26, 16))
        self.add_user_btn.setObjectName("add_user_btn")
        self.horizontalLayout_6.addWidget(self.add_user_btn)
        self.formLayout_3.setLayout(12, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_6)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(11, QtWidgets.QFormLayout.LabelRole, spacerItem14)
        self.all_users_btn = QtWidgets.QPushButton(self.add_user_box)
        self.all_users_btn.setObjectName("all_users_btn")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.all_users_btn)
        self.verticalLayout_4.addWidget(self.add_user_box)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.login_box = QtWidgets.QGroupBox(self.tab_6)
        self.login_box.setAlignment(QtCore.Qt.AlignCenter)
        self.login_box.setObjectName("login_box")
        self.formLayout_4 = QtWidgets.QFormLayout(self.login_box)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_21 = QtWidgets.QLabel(self.login_box)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.uname_entry = QtWidgets.QLineEdit(self.login_box)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uname_entry.setFont(font)
        self.uname_entry.setClearButtonEnabled(True)
        self.uname_entry.setObjectName("uname_entry")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.uname_entry)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem16)
        self.label_20 = QtWidgets.QLabel(self.login_box)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.psd_entry = QtWidgets.QLineEdit(self.login_box)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.psd_entry.setFont(font)
        self.psd_entry.setEchoMode(QtWidgets.QLineEdit.Password)
        self.psd_entry.setClearButtonEnabled(True)
        self.psd_entry.setObjectName("psd_entry")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.psd_entry)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem17)
        self.login_edit_btn = QtWidgets.QPushButton(self.login_box)
        self.login_edit_btn.setObjectName("login_edit_btn")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.login_edit_btn)
        self.verticalLayout_5.addWidget(self.login_box)
        self.edit_user_box = QtWidgets.QGroupBox(self.tab_6)
        self.edit_user_box.setEnabled(False)
        self.edit_user_box.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_user_box.setObjectName("edit_user_box")
        self.formLayout_5 = QtWidgets.QFormLayout(self.edit_user_box)
        self.formLayout_5.setObjectName("formLayout_5")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_5.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem18)
        self.label_22 = QtWidgets.QLabel(self.edit_user_box)
        self.label_22.setObjectName("label_22")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_5.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem19)
        self.label_25 = QtWidgets.QLabel(self.edit_user_box)
        self.label_25.setObjectName("label_25")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.edit_email = QtWidgets.QLineEdit(self.edit_user_box)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_email.setFont(font)
        self.edit_email.setClearButtonEnabled(True)
        self.edit_email.setObjectName("edit_email")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit_email)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_5.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem20)
        self.label_24 = QtWidgets.QLabel(self.edit_user_box)
        self.label_24.setObjectName("label_24")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.edit_psd = QtWidgets.QLineEdit(self.edit_user_box)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_psd.setFont(font)
        self.edit_psd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_psd.setClearButtonEnabled(True)
        self.edit_psd.setObjectName("edit_psd")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.edit_psd)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_5.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem21)
        self.label_23 = QtWidgets.QLabel(self.edit_user_box)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.edit_psd2 = QtWidgets.QLineEdit(self.edit_user_box)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_psd2.setFont(font)
        self.edit_psd2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_psd2.setClearButtonEnabled(True)
        self.edit_psd2.setObjectName("edit_psd2")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.edit_psd2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cancel_user_edit_btn = QtWidgets.QPushButton(self.edit_user_box)
        self.cancel_user_edit_btn.setIcon(icon8)
        self.cancel_user_edit_btn.setIconSize(QtCore.QSize(26, 16))
        self.cancel_user_edit_btn.setObjectName("cancel_user_edit_btn")
        self.horizontalLayout_7.addWidget(self.cancel_user_edit_btn)
        self.save_user_edit_btn = QtWidgets.QPushButton(self.edit_user_box)
        self.save_user_edit_btn.setIcon(icon9)
        self.save_user_edit_btn.setIconSize(QtCore.QSize(26, 16))
        self.save_user_edit_btn.setObjectName("save_user_edit_btn")
        self.horizontalLayout_7.addWidget(self.save_user_edit_btn)
        self.formLayout_5.setLayout(8, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_7)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_5.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem22)
        self.edit_uname = QtWidgets.QLineEdit(self.edit_user_box)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_uname.setFont(font)
        self.edit_uname.setClearButtonEnabled(True)
        self.edit_uname.setObjectName("edit_uname")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_uname)
        self.verticalLayout_5.addWidget(self.edit_user_box)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.MainTab.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem23, 0, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.supl_table = QtWidgets.QTableWidget(self.tab_7)
        self.supl_table.setEnabled(True)
        self.supl_table.setAutoFillBackground(True)
        self.supl_table.setObjectName("supl_table")
        self.supl_table.setColumnCount(3)
        self.supl_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.supl_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.supl_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.supl_table.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_5.addWidget(self.supl_table)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_8 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_8.setVerticalSpacing(15)
        self.formLayout_8.setObjectName("formLayout_8")
        self.search_supl = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.search_supl.setFont(font)
        self.search_supl.setText("")
        self.search_supl.setObjectName("search_supl")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.search_supl)
        self.search_supl_btn = QtWidgets.QPushButton(self.groupBox)
        self.search_supl_btn.setIcon(icon11)
        self.search_supl_btn.setIconSize(QtCore.QSize(30, 23))
        self.search_supl_btn.setObjectName("search_supl_btn")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.search_supl_btn)
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        self.label_28.setObjectName("label_28")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.supl_name_edit = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.supl_name_edit.setFont(font)
        self.supl_name_edit.setObjectName("supl_name_edit")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.supl_name_edit)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.supl_email_edit = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.supl_email_edit.setFont(font)
        self.supl_email_edit.setObjectName("supl_email_edit")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.supl_email_edit)
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setObjectName("label_27")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.supl_cont_edit = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.supl_cont_edit.setFont(font)
        self.supl_cont_edit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.supl_cont_edit.setObjectName("supl_cont_edit")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.supl_cont_edit)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.delete_supl_btn = QtWidgets.QPushButton(self.groupBox)
        self.delete_supl_btn.setEnabled(False)
        self.delete_supl_btn.setIcon(icon10)
        self.delete_supl_btn.setIconSize(QtCore.QSize(26, 16))
        self.delete_supl_btn.setObjectName("delete_supl_btn")
        self.horizontalLayout_10.addWidget(self.delete_supl_btn)
        self.save_supl_edit_btn = QtWidgets.QPushButton(self.groupBox)
        self.save_supl_edit_btn.setEnabled(False)
        self.save_supl_edit_btn.setIcon(icon9)
        self.save_supl_edit_btn.setIconSize(QtCore.QSize(26, 16))
        self.save_supl_edit_btn.setObjectName("save_supl_edit_btn")
        self.horizontalLayout_10.addWidget(self.save_supl_edit_btn)
        self.formLayout_8.setLayout(5, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_10)
        self.gridLayout_3.addWidget(self.groupBox, 0, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_6.setVerticalSpacing(29)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.supl_name_entry = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.supl_name_entry.setFont(font)
        self.supl_name_entry.setObjectName("supl_name_entry")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.supl_name_entry)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.supl_email_entry = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.supl_email_entry.setFont(font)
        self.supl_email_entry.setObjectName("supl_email_entry")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.supl_email_entry)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.supl_cont_entry = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.supl_cont_entry.setFont(font)
        self.supl_cont_entry.setObjectName("supl_cont_entry")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.supl_cont_entry)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cancel_supl_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.cancel_supl_btn.setIcon(icon8)
        self.cancel_supl_btn.setIconSize(QtCore.QSize(26, 16))
        self.cancel_supl_btn.setObjectName("cancel_supl_btn")
        self.horizontalLayout_9.addWidget(self.cancel_supl_btn)
        self.add_supl_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.add_supl_btn.setIcon(icon9)
        self.add_supl_btn.setIconSize(QtCore.QSize(26, 16))
        self.add_supl_btn.setObjectName("add_supl_btn")
        self.horizontalLayout_9.addWidget(self.add_supl_btn)
        self.formLayout_6.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_9)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.MainTab.addTab(self.tab_7, "")
        self.verticalLayout_2.addWidget(self.MainTab)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 724, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.MainTab.setCurrentIndex(0)
        self.products_tab.setCurrentIndex(2)
        self.MainTab.currentChanged['int'].connect(self.supl_name_entry.setFocus)
        self.products_tab.currentChanged['int'].connect(self.p_name_entry.setFocus)
        self.products_tab.currentChanged['int'].connect(self.search_prod_entry.setFocus)
        self.MainTab.currentChanged['int'].connect(self.add_uname.setFocus)
        self.MainTab.currentChanged['int'].connect(self.supl_name_entry.setFocus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Masewa Beauty & Cosmetics"))
        self.sales_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Sales</span></p></body></html>"))
        self.sales_btn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>asfsdf</p></body></html>"))
        self.products_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Products</span></p></body></html>"))
        self.users_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Users</span></p></body></html>"))
        self.suppliers_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Suppliers</span></p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "LIST OF ALL SALES"))
        item = self.sales_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product\'s Name"))
        item = self.sales_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Unit Cost"))
        item = self.sales_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Quantity Sold"))
        item = self.sales_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total Cost"))
        item = self.sales_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date Sold"))
        item = self.sales_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Remaining"))
        self.add_sales_btn.setText(_translate("MainWindow", "Add A New Sale"))
        self.refresh_btn.setText(_translate("MainWindow", "Refresh"))
        self.export_btn.setText(_translate("MainWindow", "Export as Excel File"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        item = self.products_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product\'s Name"))
        item = self.products_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.products_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price"))
        item = self.products_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Category"))
        item = self.products_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date Re-stocked"))
        item = self.products_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Supplier\'s Name"))
        self.products_tab.setTabText(self.products_tab.indexOf(self.tab_3), _translate("MainWindow", "All Products"))
        self.label_5.setText(_translate("MainWindow", "Product\'s Name"))
        self.label.setText(_translate("MainWindow", "Category"))
        self.label_2.setText(_translate("MainWindow", "Product\'s Price"))
        self.label_3.setText(_translate("MainWindow", "Product Quantity"))
        self.label_4.setText(_translate("MainWindow", "Supplier\'s Name"))
        self.p_supl_entry.setPlaceholderText(_translate("MainWindow", "(optional)"))
        self.cancel_prod_btn.setText(_translate("MainWindow", "Cancel"))
        self.categories_btn.setText(_translate("MainWindow", "Add Category"))
        self.save_prod_btn.setText(_translate("MainWindow", "Save"))
        self.add_categ_entry.setPlaceholderText(_translate("MainWindow", "Name of new category"))
        self.new_categ_btn.setText(_translate("MainWindow", "Add"))
        self.products_tab.setTabText(self.products_tab.indexOf(self.tab_4), _translate("MainWindow", "Add A New Product"))
        self.label_8.setText(_translate("MainWindow", "Supplier\'s Name"))
        self.search_prod_entry.setPlaceholderText(_translate("MainWindow", "search by Name"))
        self.delete_prod_btn.setText(_translate("MainWindow", "Delete"))
        self.save_prod_edit_btn.setText(_translate("MainWindow", "Save Changes"))
        self.label_10.setText(_translate("MainWindow", "Product\'s Name"))
        self.label_9.setText(_translate("MainWindow", "Category"))
        self.search_prod_btn.setText(_translate("MainWindow", "Search"))
        self.label_11.setText(_translate("MainWindow", "Product Quantity"))
        self.label_7.setText(_translate("MainWindow", "Product\'s Price"))
        self.products_tab.setTabText(self.products_tab.indexOf(self.tab_5), _translate("MainWindow", "Edit or Delete A Product"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.add_user_box.setTitle(_translate("MainWindow", "ADD A NEW USER"))
        self.label_12.setText(_translate("MainWindow", "Username"))
        self.label_13.setText(_translate("MainWindow", "E-mail"))
        self.add_email.setPlaceholderText(_translate("MainWindow", "example@gmail.com"))
        self.label_14.setText(_translate("MainWindow", "Password"))
        self.label_15.setText(_translate("MainWindow", "Confirm Password"))
        self.cancel_user_btn.setText(_translate("MainWindow", "Cancel"))
        self.add_user_btn.setText(_translate("MainWindow", "Add This User"))
        self.all_users_btn.setText(_translate("MainWindow", "See All Users"))
        self.login_box.setTitle(_translate("MainWindow", "LOGIN"))
        self.label_21.setText(_translate("MainWindow", "Username"))
        self.label_20.setText(_translate("MainWindow", "Password"))
        self.login_edit_btn.setText(_translate("MainWindow", "Login To Change My Details"))
        self.edit_user_box.setTitle(_translate("MainWindow", "EDIT USER DETAILS"))
        self.label_22.setText(_translate("MainWindow", "Username"))
        self.label_25.setText(_translate("MainWindow", "E-mail"))
        self.label_24.setText(_translate("MainWindow", "Password"))
        self.label_23.setText(_translate("MainWindow", "Confirm Password"))
        self.cancel_user_edit_btn.setText(_translate("MainWindow", "Cancel"))
        self.save_user_edit_btn.setText(_translate("MainWindow", "Save Changes"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.tab_6), _translate("MainWindow", "Page"))
        self.supl_table.setSortingEnabled(True)
        item = self.supl_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Supplier\'s Name"))
        item = self.supl_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Supplier\'s E-mail"))
        item = self.supl_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Suppliers Contact"))
        self.groupBox.setTitle(_translate("MainWindow", "EDIT SUPPLIER\'S INFO"))
        self.search_supl.setPlaceholderText(_translate("MainWindow", "Enter the supplier\'s name here"))
        self.search_supl_btn.setText(_translate("MainWindow", "Search Supplier"))
        self.label_28.setText(_translate("MainWindow", "Supplier\'s Name"))
        self.label_19.setText(_translate("MainWindow", "Supplier\'s Email"))
        self.label_27.setText(_translate("MainWindow", "Supplier\'s Conact"))
        self.delete_supl_btn.setText(_translate("MainWindow", "Delete"))
        self.save_supl_edit_btn.setText(_translate("MainWindow", "Save Changes"))
        self.groupBox_2.setTitle(_translate("MainWindow", "NEW SUPPLIER"))
        self.label_16.setText(_translate("MainWindow", "Supllier\'s Name"))
        self.label_17.setText(_translate("MainWindow", "Supplier\'s Email"))
        self.supl_email_entry.setPlaceholderText(_translate("MainWindow", "supplier@gmail.com"))
        self.label_18.setText(_translate("MainWindow", "Supplier\'s Conact"))
        self.supl_cont_entry.setPlaceholderText(_translate("MainWindow", "(optional)"))
        self.cancel_supl_btn.setText(_translate("MainWindow", "Cancel"))
        self.add_supl_btn.setText(_translate("MainWindow", "Add Supplier"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.tab_7), _translate("MainWindow", "Page"))
import icons_rc
