# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sales.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sales_win(object):
    def setupUi(self, sales_win):
        sales_win.setObjectName("sales_win")
        sales_win.setWindowModality(QtCore.Qt.ApplicationModal)
        sales_win.resize(400, 300)
        sales_win.setMinimumSize(QtCore.QSize(400, 300))
        sales_win.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/gallery/money.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        sales_win.setWindowIcon(icon)
        self.cancel_sales_btn = QtWidgets.QPushButton(sales_win)
        self.cancel_sales_btn.setGeometry(QtCore.QRect(50, 240, 101, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/gallery/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_sales_btn.setIcon(icon1)
        self.cancel_sales_btn.setIconSize(QtCore.QSize(26, 16))
        self.cancel_sales_btn.setObjectName("cancel_sales_btn")
        self.unit_price_lbl = QtWidgets.QLabel(sales_win)
        self.unit_price_lbl.setGeometry(QtCore.QRect(240, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.unit_price_lbl.setFont(font)
        self.unit_price_lbl.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.unit_price_lbl.setObjectName("unit_price_lbl")
        self.send_sales_btn = QtWidgets.QPushButton(sales_win)
        self.send_sales_btn.setGeometry(QtCore.QRect(250, 240, 101, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/gallery/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_sales_btn.setIcon(icon2)
        self.send_sales_btn.setIconSize(QtCore.QSize(26, 20))
        self.send_sales_btn.setObjectName("send_sales_btn")
        self.label_3 = QtWidgets.QLabel(sales_win)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(sales_win)
        self.label_5.setGeometry(QtCore.QRect(40, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.total_price_lbl = QtWidgets.QLabel(sales_win)
        self.total_price_lbl.setGeometry(QtCore.QRect(250, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.total_price_lbl.setFont(font)
        self.total_price_lbl.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.total_price_lbl.setObjectName("total_price_lbl")
        self.label = QtWidgets.QLabel(sales_win)
        self.label.setGeometry(QtCore.QRect(40, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(sales_win)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.prod_name_combo = QtWidgets.QComboBox(sales_win)
        self.prod_name_combo.setGeometry(QtCore.QRect(190, 30, 141, 31))
        self.prod_name_combo.setEditable(False)
        self.prod_name_combo.setCurrentText("")
        self.prod_name_combo.setObjectName("prod_name_combo")
        self.spinBox = QtWidgets.QSpinBox(sales_win)
        self.spinBox.setGeometry(QtCore.QRect(190, 130, 71, 22))
        self.spinBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox.setWrapping(False)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox.setProperty("showGroupSeparator", False)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(20)
        self.spinBox.setObjectName("spinBox")
        self.label_4 = QtWidgets.QLabel(sales_win)
        self.label_4.setGeometry(QtCore.QRect(190, 180, 51, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.unit_price_lbl_2 = QtWidgets.QLabel(sales_win)
        self.unit_price_lbl_2.setGeometry(QtCore.QRect(190, 80, 41, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.unit_price_lbl_2.setFont(font)
        self.unit_price_lbl_2.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.unit_price_lbl_2.setObjectName("unit_price_lbl_2")
        self.label.setBuddy(self.prod_name_combo)

        self.retranslateUi(sales_win)
        self.prod_name_combo.setCurrentIndex(-1)
        self.cancel_sales_btn.clicked.connect(sales_win.close)
        QtCore.QMetaObject.connectSlotsByName(sales_win)

    def retranslateUi(self, sales_win):
        _translate = QtCore.QCoreApplication.translate
        sales_win.setWindowTitle(_translate("sales_win", "Add Sales"))
        self.cancel_sales_btn.setText(_translate("sales_win", "Cancel"))
        self.unit_price_lbl.setText(_translate("sales_win", " 000"))
        self.send_sales_btn.setText(_translate("sales_win", "Okay"))
        self.label_3.setText(_translate("sales_win", "TOTAL PRICE "))
        self.label_5.setText(_translate("sales_win", "Unit Price"))
        self.total_price_lbl.setText(_translate("sales_win", "0000"))
        self.label.setText(_translate("sales_win", "Product\'s Name"))
        self.label_2.setText(_translate("sales_win", "Quantity"))
        self.label_4.setText(_translate("sales_win", "Ksh"))
        self.unit_price_lbl_2.setText(_translate("sales_win", "Ksh"))
import icons_rc
